name: GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your branch name if different (e.g., `gh-pages`)
  pull_request:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Adjust this based on your Jekyll version if necessary

    - name: Install dependencies
      run: |
        gem install jekyll bundler
        bundle install

    - name: Build the site with Jekyll
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

